apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: quay-operator
  namespace: quay-registry
spec:
  # This is the official Red Hat Quay Operator
  name: quay-operator
  # This catalog is available by default on OpenShift
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  
  # --- THE FIX ---
  # Change 'stable' to a specific, valid channel
  channel: stable-3.15 
  
  installPlanApproval: Automatic